-   id: test-nops-cli
    name: Test NOPS CLI
    description: This hook will test NOPS CLI
    entry: nops-cli --hello-world Shreyas
    language: python
    language_version: "3.8"
    additional_dependencies: ["jsondiff"]
    #types: [text]

-   id: nops-hook
    name: nOps Hello World Hook
    description: This hook is hello world hook
    entry: nops-cli  --get_accounts
    language: python
    language_version: "3.8"
    additional_dependencies: ["jsondiff"]
#    python_venv: venv
