repos:
-   repo: local
    rev: v1.2.3
    hooks:
    -   id: nops-hook
        name: nOps Pricing Hook
        description: This hook is hello world hook
        entry: nops-cli  --tf_dir terraform --pricing
        language: python
        language_version: "3.8"
        additional_dependencies: ["jsondiff"]
