-   id: nops-hook
    name: nOps Pricing Hook
    description: This hook is hello world hook
    entry: nops-cli --pricing --iac-type terraform
    language: python
    language_version: "3.9"
    additional_dependencies: ["jsondiff", "/Users/yograj/Documents/nops_sdk-0.2.1.tar.gz"]
    files: (\.tf)$
    exclude: \.terraform\/.*$
