-   id: nops-hook
    name: nOps Pricing Hook
    description: This hook is hello world hook
    entry: nops-cli --pricing --iac-type terraform
    language: python
    language_version: "3.8"
    additional_dependencies: ["jsondiff"]
    files: (\.tf)$
    exclude: \.terraform\/.*$
